const ActionTypes = {
  TOGGLE_MENU: "TOGGLE_MENU",
  FETCH_FLIGHT_REQUESTED: "FETCH_FLIGHT_REQUESTED",
  FETCH_FLIGHT_SUCCEEDED: "FETCH_FLIGHT_SUCCEEDED",
  FETCH_FLIGHT_FAILED: "FETCH_FLIGHT_FAILED",
  LOAD_PAGE: "LOAD_PAGE"
};
export default ActionTypes;
